# Generated by Django 2.2.14 on 2021-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210424_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HF', 'Haifa'), ('HZ', 'Herzliya'), ('TLV', 'Tel-Aviv'), ('As', 'Ashkelon'), ('EL', 'Eilat')], max_length=2),
        ),
    ]
