# Generated by Django 2.2.14 on 2021-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210425_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HF', 'Haifa'), ('HZ', 'Herzliya'), ('TV', 'Tel-Aviv'), ('As', 'Ashdod'), ('EL', 'Eilat')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('M', 'Motor yacht'), ('S', 'Sailboat'), ('T', 'Tender Boat')], max_length=1),
        ),
    ]
