# Generated by Django 2.2.14 on 2021-06-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210611_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
