# Generated by Django 2.2.14 on 2021-06-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='timestamp',
            new_name='invited_date',
        ),
    ]
