# Generated by Django 2.2.14 on 2021-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210622_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='invited_date',
            field=models.DateTimeField(),
        ),
    ]
