# Generated by Django 2.2.14 on 2021-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210622_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='invited_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
