# Generated by Django 2.2.14 on 2021-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210629_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='invited_date',
            field=models.DateTimeField(),
        ),
    ]
