# Generated by Django 2.2.14 on 2021-08-11 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210718_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invited_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
